version = 0.1
[default.deploy.parameters]
stack_name = "plantuml-generator"
resolve_s3 = true
s3_prefix = "plantuml-generator"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
